# Generated by Django 5.2 on 2025-05-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenro_a', models.CharField(blank=True, max_length=20, null=True)),
                ('cliced_a', models.CharField(blank=True, max_length=20, null=True)),
                ('rescierre', models.DateField(blank=True, null=True)),
                ('resvto', models.DateField(blank=True, null=True)),
                ('cliente_desde', models.DateField(blank=True, null=True)),
                ('tarven', models.DateField(blank=True, null=True)),
                ('cliapeuno', models.CharField(blank=True, max_length=100, null=True)),
                ('cliapedos', models.CharField(blank=True, max_length=100, null=True)),
                ('clinomuno', models.CharField(blank=True, max_length=100, null=True)),
                ('clinomdos', models.CharField(blank=True, max_length=100, null=True)),
                ('telt', models.CharField(blank=True, max_length=20, null=True)),
                ('cel1', models.CharField(blank=True, max_length=20, null=True)),
                ('cel2', models.CharField(blank=True, max_length=20, null=True)),
                ('telbau', models.CharField(blank=True, max_length=20, null=True)),
                ('telweb', models.CharField(blank=True, max_length=20, null=True)),
                ('celweb', models.CharField(blank=True, max_length=20, null=True)),
                ('surco_vida', models.CharField(blank=True, max_length=50, null=True)),
                ('surco_hogar', models.CharField(blank=True, max_length=50, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('fecha_carga', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_cargados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('venta', 'Venta'), ('rechazo', 'Rechazo'), ('pendiente', 'Pendiente'), ('rellamar', 'Rellamar'), ('llamar_mañana', 'Llamar de mañana'), ('llamar_tarde', 'Llamar de tarde'), ('llamar_sabado', 'Llamar sábado'), ('no_target', 'No target'), ('dato_erroneo', 'Dato erróneo')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='App.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
