# Generated by Django 5.2 on 2025-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
