# Generated by Django 5.2 on 2025-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
