# Generated by Django 5.2 on 2025-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cliente_telefono_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_venta',
        ),
        migrations.AddField(
            model_name='gestion',
            name='telefono_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
