# Generated by Django 5.2 on 2025-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_cliente_telefono_venta_gestion_telefono_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='mes_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
