# Generated by Django 5.2 on 2025-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_gestion_mes_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='departamento',
            field=models.CharField(blank=True, default='MONTEVIDEO', max_length=100),
        ),
        migrations.AddField(
            model_name='gestion',
            name='domicilio_apto',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='gestion',
            name='domicilio_calle',
            field=models.CharField(blank=True, default='ITUZAINGÓ', max_length=100),
        ),
        migrations.AddField(
            model_name='gestion',
            name='domicilio_numero',
            field=models.CharField(blank=True, default='1315', max_length=10),
        ),
        migrations.AddField(
            model_name='gestion',
            name='localidad',
            field=models.CharField(blank=True, default='MONTEVIDEO', max_length=100),
        ),
        migrations.AddField(
            model_name='gestion',
            name='poliza',
            field=models.CharField(blank=True, default='110316', max_length=20),
        ),
        migrations.AddField(
            model_name='gestion',
            name='telefono',
            field=models.CharField(blank=True, default='18918', max_length=20),
        ),
    ]
