# Generated by Django 5.2 on 2025-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_gestion_departamento_gestion_domicilio_apto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='domicilio_apto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='domicilio_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='domicilio_numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='poliza',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
