# Generated by Django 5.2 on 2025-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_gestion_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='email_venta',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
