# Generated by Django 5.2 on 2025-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_gestion_email_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='inmueble',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='paredes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='seguridad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='techo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='vivienda',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
